# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='gallery_image',
            field=models.ImageField(blank=True, upload_to='static/pix/'),
        ),
    ]
